server:
  port: 18080

spring:
  application:
    name: backend-spring-kotlin-example
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates/
    check-template-location: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
